// Code generated by entc, DO NOT EDIT.

package employee

const (
	// Label holds the string label denoting the employee type in the database.
	Label = "employee"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"

	// EdgeStatistic holds the string denoting the statistic edge name in mutations.
	EdgeStatistic = "statistic"

	// Table holds the table name of the employee in the database.
	Table = "employees"
	// StatisticTable is the table the holds the statistic relation/edge.
	StatisticTable = "statistics"
	// StatisticInverseTable is the table name for the Statistic entity.
	// It exists in this package in order to avoid circular dependency with the "statistic" package.
	StatisticInverseTable = "statistics"
	// StatisticColumn is the table column denoting the statistic relation/edge.
	StatisticColumn = "employee_statistic"
)

// Columns holds all SQL columns for employee fields.
var Columns = []string{
	FieldID,
	FieldEmail,
	FieldName,
	FieldUserID,
}
