// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Area is the predicate function for area builders.
type Area func(*sql.Selector)

// Carrier is the predicate function for carrier builders.
type Carrier func(*sql.Selector)

// Contagious is the predicate function for contagious builders.
type Contagious func(*sql.Selector)

// Employee is the predicate function for employee builders.
type Employee func(*sql.Selector)

// Patient is the predicate function for patient builders.
type Patient func(*sql.Selector)

// Statistic is the predicate function for statistic builders.
type Statistic func(*sql.Selector)
