// Code generated by entc, DO NOT EDIT.

package statistic

const (
	// Label holds the string label denoting the statistic type in the database.
	Label = "statistic"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"

	// EdgeEmployee holds the string denoting the employee edge name in mutations.
	EdgeEmployee = "employee"
	// EdgeContagious holds the string denoting the contagious edge name in mutations.
	EdgeContagious = "contagious"
	// EdgeCarrier holds the string denoting the carrier edge name in mutations.
	EdgeCarrier = "carrier"
	// EdgePatient holds the string denoting the patient edge name in mutations.
	EdgePatient = "patient"
	// EdgeArea holds the string denoting the area edge name in mutations.
	EdgeArea = "area"

	// Table holds the table name of the statistic in the database.
	Table = "statistics"
	// EmployeeTable is the table the holds the employee relation/edge.
	EmployeeTable = "statistics"
	// EmployeeInverseTable is the table name for the Employee entity.
	// It exists in this package in order to avoid circular dependency with the "employee" package.
	EmployeeInverseTable = "employees"
	// EmployeeColumn is the table column denoting the employee relation/edge.
	EmployeeColumn = "employee_statistic"
	// ContagiousTable is the table the holds the contagious relation/edge.
	ContagiousTable = "statistics"
	// ContagiousInverseTable is the table name for the Contagious entity.
	// It exists in this package in order to avoid circular dependency with the "contagious" package.
	ContagiousInverseTable = "contagious"
	// ContagiousColumn is the table column denoting the contagious relation/edge.
	ContagiousColumn = "contagious_statistic"
	// CarrierTable is the table the holds the carrier relation/edge.
	CarrierTable = "statistics"
	// CarrierInverseTable is the table name for the Carrier entity.
	// It exists in this package in order to avoid circular dependency with the "carrier" package.
	CarrierInverseTable = "carriers"
	// CarrierColumn is the table column denoting the carrier relation/edge.
	CarrierColumn = "carrier_statistic"
	// PatientTable is the table the holds the patient relation/edge.
	PatientTable = "statistics"
	// PatientInverseTable is the table name for the Patient entity.
	// It exists in this package in order to avoid circular dependency with the "patient" package.
	PatientInverseTable = "patients"
	// PatientColumn is the table column denoting the patient relation/edge.
	PatientColumn = "patient_statistic"
	// AreaTable is the table the holds the area relation/edge.
	AreaTable = "statistics"
	// AreaInverseTable is the table name for the Area entity.
	// It exists in this package in order to avoid circular dependency with the "area" package.
	AreaInverseTable = "areas"
	// AreaColumn is the table column denoting the area relation/edge.
	AreaColumn = "area_statistic"
)

// Columns holds all SQL columns for statistic fields.
var Columns = []string{
	FieldID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Statistic type.
var ForeignKeys = []string{
	"area_statistic",
	"carrier_statistic",
	"contagious_statistic",
	"employee_statistic",
	"patient_statistic",
}
