// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/SrtStory/app/ent/area"
	"github.com/facebookincubator/ent/dialect/sql"
)

// Area is the model entity for the Area schema.
type Area struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "Name" field.
	Name string `json:"Name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AreaQuery when eager-loading is set.
	Edges AreaEdges `json:"edges"`
}

// AreaEdges holds the relations/edges for other nodes in the graph.
type AreaEdges struct {
	// Statistic holds the value of the statistic edge.
	Statistic []*Statistic
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// StatisticOrErr returns the Statistic value or an error if the edge
// was not loaded in eager-loading.
func (e AreaEdges) StatisticOrErr() ([]*Statistic, error) {
	if e.loadedTypes[0] {
		return e.Statistic, nil
	}
	return nil, &NotLoadedError{edge: "statistic"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Area) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // Name
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Area fields.
func (a *Area) assignValues(values ...interface{}) error {
	if m, n := len(values), len(area.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	a.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field Name", values[0])
	} else if value.Valid {
		a.Name = value.String
	}
	return nil
}

// QueryStatistic queries the statistic edge of the Area.
func (a *Area) QueryStatistic() *StatisticQuery {
	return (&AreaClient{config: a.config}).QueryStatistic(a)
}

// Update returns a builder for updating this Area.
// Note that, you need to call Area.Unwrap() before calling this method, if this Area
// was returned from a transaction, and the transaction was committed or rolled back.
func (a *Area) Update() *AreaUpdateOne {
	return (&AreaClient{config: a.config}).UpdateOne(a)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (a *Area) Unwrap() *Area {
	tx, ok := a.config.driver.(*txDriver)
	if !ok {
		panic("ent: Area is not a transactional entity")
	}
	a.config.driver = tx.drv
	return a
}

// String implements the fmt.Stringer.
func (a *Area) String() string {
	var builder strings.Builder
	builder.WriteString("Area(")
	builder.WriteString(fmt.Sprintf("id=%v", a.ID))
	builder.WriteString(", Name=")
	builder.WriteString(a.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Areas is a parsable slice of Area.
type Areas []*Area

func (a Areas) config(cfg config) {
	for _i := range a {
		a[_i].config = cfg
	}
}
