// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/SrtStory/app/ent/carrier"
	"github.com/SrtStory/app/ent/predicate"
	"github.com/SrtStory/app/ent/statistic"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// CarrierUpdate is the builder for updating Carrier entities.
type CarrierUpdate struct {
	config
	hooks      []Hook
	mutation   *CarrierMutation
	predicates []predicate.Carrier
}

// Where adds a new predicate for the builder.
func (cu *CarrierUpdate) Where(ps ...predicate.Carrier) *CarrierUpdate {
	cu.predicates = append(cu.predicates, ps...)
	return cu
}

// SetName sets the Name field.
func (cu *CarrierUpdate) SetName(s string) *CarrierUpdate {
	cu.mutation.SetName(s)
	return cu
}

// AddStatisticIDs adds the statistic edge to Statistic by ids.
func (cu *CarrierUpdate) AddStatisticIDs(ids ...int) *CarrierUpdate {
	cu.mutation.AddStatisticIDs(ids...)
	return cu
}

// AddStatistic adds the statistic edges to Statistic.
func (cu *CarrierUpdate) AddStatistic(s ...*Statistic) *CarrierUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return cu.AddStatisticIDs(ids...)
}

// Mutation returns the CarrierMutation object of the builder.
func (cu *CarrierUpdate) Mutation() *CarrierMutation {
	return cu.mutation
}

// RemoveStatisticIDs removes the statistic edge to Statistic by ids.
func (cu *CarrierUpdate) RemoveStatisticIDs(ids ...int) *CarrierUpdate {
	cu.mutation.RemoveStatisticIDs(ids...)
	return cu
}

// RemoveStatistic removes statistic edges to Statistic.
func (cu *CarrierUpdate) RemoveStatistic(s ...*Statistic) *CarrierUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return cu.RemoveStatisticIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (cu *CarrierUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := cu.mutation.Name(); ok {
		if err := carrier.NameValidator(v); err != nil {
			return 0, &ValidationError{Name: "Name", err: fmt.Errorf("ent: validator failed for field \"Name\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(cu.hooks) == 0 {
		affected, err = cu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CarrierMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cu.mutation = mutation
			affected, err = cu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cu.hooks) - 1; i >= 0; i-- {
			mut = cu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CarrierUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CarrierUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CarrierUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cu *CarrierUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   carrier.Table,
			Columns: carrier.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: carrier.FieldID,
			},
		},
	}
	if ps := cu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: carrier.FieldName,
		})
	}
	if nodes := cu.mutation.RemovedStatisticIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carrier.StatisticTable,
			Columns: []string{carrier.StatisticColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: statistic.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.StatisticIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carrier.StatisticTable,
			Columns: []string{carrier.StatisticColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: statistic.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{carrier.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// CarrierUpdateOne is the builder for updating a single Carrier entity.
type CarrierUpdateOne struct {
	config
	hooks    []Hook
	mutation *CarrierMutation
}

// SetName sets the Name field.
func (cuo *CarrierUpdateOne) SetName(s string) *CarrierUpdateOne {
	cuo.mutation.SetName(s)
	return cuo
}

// AddStatisticIDs adds the statistic edge to Statistic by ids.
func (cuo *CarrierUpdateOne) AddStatisticIDs(ids ...int) *CarrierUpdateOne {
	cuo.mutation.AddStatisticIDs(ids...)
	return cuo
}

// AddStatistic adds the statistic edges to Statistic.
func (cuo *CarrierUpdateOne) AddStatistic(s ...*Statistic) *CarrierUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return cuo.AddStatisticIDs(ids...)
}

// Mutation returns the CarrierMutation object of the builder.
func (cuo *CarrierUpdateOne) Mutation() *CarrierMutation {
	return cuo.mutation
}

// RemoveStatisticIDs removes the statistic edge to Statistic by ids.
func (cuo *CarrierUpdateOne) RemoveStatisticIDs(ids ...int) *CarrierUpdateOne {
	cuo.mutation.RemoveStatisticIDs(ids...)
	return cuo
}

// RemoveStatistic removes statistic edges to Statistic.
func (cuo *CarrierUpdateOne) RemoveStatistic(s ...*Statistic) *CarrierUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return cuo.RemoveStatisticIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (cuo *CarrierUpdateOne) Save(ctx context.Context) (*Carrier, error) {
	if v, ok := cuo.mutation.Name(); ok {
		if err := carrier.NameValidator(v); err != nil {
			return nil, &ValidationError{Name: "Name", err: fmt.Errorf("ent: validator failed for field \"Name\": %w", err)}
		}
	}

	var (
		err  error
		node *Carrier
	)
	if len(cuo.hooks) == 0 {
		node, err = cuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CarrierMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cuo.mutation = mutation
			node, err = cuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cuo.hooks) - 1; i >= 0; i-- {
			mut = cuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CarrierUpdateOne) SaveX(ctx context.Context) *Carrier {
	c, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return c
}

// Exec executes the query on the entity.
func (cuo *CarrierUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CarrierUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cuo *CarrierUpdateOne) sqlSave(ctx context.Context) (c *Carrier, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   carrier.Table,
			Columns: carrier.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: carrier.FieldID,
			},
		},
	}
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Carrier.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := cuo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: carrier.FieldName,
		})
	}
	if nodes := cuo.mutation.RemovedStatisticIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carrier.StatisticTable,
			Columns: []string{carrier.StatisticColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: statistic.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.StatisticIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carrier.StatisticTable,
			Columns: []string{carrier.StatisticColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: statistic.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	c = &Carrier{config: cuo.config}
	_spec.Assign = c.assignValues
	_spec.ScanValues = c.scanValues()
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{carrier.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return c, nil
}
