// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/SrtStory/app/ent/contagious"
	"github.com/SrtStory/app/ent/predicate"
	"github.com/SrtStory/app/ent/statistic"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// ContagiousUpdate is the builder for updating Contagious entities.
type ContagiousUpdate struct {
	config
	hooks      []Hook
	mutation   *ContagiousMutation
	predicates []predicate.Contagious
}

// Where adds a new predicate for the builder.
func (cu *ContagiousUpdate) Where(ps ...predicate.Contagious) *ContagiousUpdate {
	cu.predicates = append(cu.predicates, ps...)
	return cu
}

// SetName sets the Name field.
func (cu *ContagiousUpdate) SetName(s string) *ContagiousUpdate {
	cu.mutation.SetName(s)
	return cu
}

// AddStatisticIDs adds the statistic edge to Statistic by ids.
func (cu *ContagiousUpdate) AddStatisticIDs(ids ...int) *ContagiousUpdate {
	cu.mutation.AddStatisticIDs(ids...)
	return cu
}

// AddStatistic adds the statistic edges to Statistic.
func (cu *ContagiousUpdate) AddStatistic(s ...*Statistic) *ContagiousUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return cu.AddStatisticIDs(ids...)
}

// Mutation returns the ContagiousMutation object of the builder.
func (cu *ContagiousUpdate) Mutation() *ContagiousMutation {
	return cu.mutation
}

// RemoveStatisticIDs removes the statistic edge to Statistic by ids.
func (cu *ContagiousUpdate) RemoveStatisticIDs(ids ...int) *ContagiousUpdate {
	cu.mutation.RemoveStatisticIDs(ids...)
	return cu
}

// RemoveStatistic removes statistic edges to Statistic.
func (cu *ContagiousUpdate) RemoveStatistic(s ...*Statistic) *ContagiousUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return cu.RemoveStatisticIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (cu *ContagiousUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(cu.hooks) == 0 {
		affected, err = cu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ContagiousMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cu.mutation = mutation
			affected, err = cu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cu.hooks) - 1; i >= 0; i-- {
			mut = cu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (cu *ContagiousUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *ContagiousUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *ContagiousUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cu *ContagiousUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   contagious.Table,
			Columns: contagious.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: contagious.FieldID,
			},
		},
	}
	if ps := cu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: contagious.FieldName,
		})
	}
	if nodes := cu.mutation.RemovedStatisticIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   contagious.StatisticTable,
			Columns: []string{contagious.StatisticColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: statistic.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.StatisticIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   contagious.StatisticTable,
			Columns: []string{contagious.StatisticColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: statistic.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{contagious.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// ContagiousUpdateOne is the builder for updating a single Contagious entity.
type ContagiousUpdateOne struct {
	config
	hooks    []Hook
	mutation *ContagiousMutation
}

// SetName sets the Name field.
func (cuo *ContagiousUpdateOne) SetName(s string) *ContagiousUpdateOne {
	cuo.mutation.SetName(s)
	return cuo
}

// AddStatisticIDs adds the statistic edge to Statistic by ids.
func (cuo *ContagiousUpdateOne) AddStatisticIDs(ids ...int) *ContagiousUpdateOne {
	cuo.mutation.AddStatisticIDs(ids...)
	return cuo
}

// AddStatistic adds the statistic edges to Statistic.
func (cuo *ContagiousUpdateOne) AddStatistic(s ...*Statistic) *ContagiousUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return cuo.AddStatisticIDs(ids...)
}

// Mutation returns the ContagiousMutation object of the builder.
func (cuo *ContagiousUpdateOne) Mutation() *ContagiousMutation {
	return cuo.mutation
}

// RemoveStatisticIDs removes the statistic edge to Statistic by ids.
func (cuo *ContagiousUpdateOne) RemoveStatisticIDs(ids ...int) *ContagiousUpdateOne {
	cuo.mutation.RemoveStatisticIDs(ids...)
	return cuo
}

// RemoveStatistic removes statistic edges to Statistic.
func (cuo *ContagiousUpdateOne) RemoveStatistic(s ...*Statistic) *ContagiousUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return cuo.RemoveStatisticIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (cuo *ContagiousUpdateOne) Save(ctx context.Context) (*Contagious, error) {

	var (
		err  error
		node *Contagious
	)
	if len(cuo.hooks) == 0 {
		node, err = cuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ContagiousMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cuo.mutation = mutation
			node, err = cuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cuo.hooks) - 1; i >= 0; i-- {
			mut = cuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *ContagiousUpdateOne) SaveX(ctx context.Context) *Contagious {
	c, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return c
}

// Exec executes the query on the entity.
func (cuo *ContagiousUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *ContagiousUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cuo *ContagiousUpdateOne) sqlSave(ctx context.Context) (c *Contagious, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   contagious.Table,
			Columns: contagious.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: contagious.FieldID,
			},
		},
	}
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Contagious.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := cuo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: contagious.FieldName,
		})
	}
	if nodes := cuo.mutation.RemovedStatisticIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   contagious.StatisticTable,
			Columns: []string{contagious.StatisticColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: statistic.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.StatisticIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   contagious.StatisticTable,
			Columns: []string{contagious.StatisticColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: statistic.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	c = &Contagious{config: cuo.config}
	_spec.Assign = c.assignValues
	_spec.ScanValues = c.scanValues()
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{contagious.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return c, nil
}
