// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/SrtStory/app/ent/carrier"
	"github.com/SrtStory/app/ent/schema"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	carrierFields := schema.Carrier{}.Fields()
	_ = carrierFields
	// carrierDescName is the schema descriptor for Name field.
	carrierDescName := carrierFields[0].Descriptor()
	// carrier.NameValidator is a validator for the "Name" field. It is called by the builders before save.
	carrier.NameValidator = carrierDescName.Validators[0].(func(string) error)
}
