/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Statistic
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntStatistic,
    EntStatisticFromJSON,
    EntStatisticFromJSONTyped,
    EntStatisticToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntAreaEdges
 */
export interface EntAreaEdges {
    /**
     * Statistic holds the value of the statistic edge.
     * @type {Array<EntStatistic>}
     * @memberof EntAreaEdges
     */
    statistic?: Array<EntStatistic>;
}

export function EntAreaEdgesFromJSON(json: any): EntAreaEdges {
    return EntAreaEdgesFromJSONTyped(json, false);
}

export function EntAreaEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntAreaEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'statistic': !exists(json, 'statistic') ? undefined : ((json['statistic'] as Array<any>).map(EntStatisticFromJSON)),
    };
}

export function EntAreaEdgesToJSON(value?: EntAreaEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'statistic': value.statistic === undefined ? undefined : ((value.statistic as Array<any>).map(EntStatisticToJSON)),
    };
}


