/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Statistic
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntCarrierEdges,
    EntCarrierEdgesFromJSON,
    EntCarrierEdgesFromJSONTyped,
    EntCarrierEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntCarrier
 */
export interface EntCarrier {
    /**
     * Name holds the value of the "Name" field.
     * @type {string}
     * @memberof EntCarrier
     */
    name?: string;
    /**
     * 
     * @type {EntCarrierEdges}
     * @memberof EntCarrier
     */
    edges?: EntCarrierEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntCarrier
     */
    id?: number;
}

export function EntCarrierFromJSON(json: any): EntCarrier {
    return EntCarrierFromJSONTyped(json, false);
}

export function EntCarrierFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntCarrier {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'edges': !exists(json, 'edges') ? undefined : EntCarrierEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntCarrierToJSON(value?: EntCarrier | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.name,
        'edges': EntCarrierEdgesToJSON(value.edges),
        'id': value.id,
    };
}


