// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// AreasColumns holds the columns for the "areas" table.
	AreasColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
	}
	// AreasTable holds the schema information for the "areas" table.
	AreasTable = &schema.Table{
		Name:        "areas",
		Columns:     AreasColumns,
		PrimaryKey:  []*schema.Column{AreasColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// CarriersColumns holds the columns for the "carriers" table.
	CarriersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
	}
	// CarriersTable holds the schema information for the "carriers" table.
	CarriersTable = &schema.Table{
		Name:        "carriers",
		Columns:     CarriersColumns,
		PrimaryKey:  []*schema.Column{CarriersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// ContagiousColumns holds the columns for the "contagious" table.
	ContagiousColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
	}
	// ContagiousTable holds the schema information for the "contagious" table.
	ContagiousTable = &schema.Table{
		Name:        "contagious",
		Columns:     ContagiousColumns,
		PrimaryKey:  []*schema.Column{ContagiousColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// EmployeesColumns holds the columns for the "employees" table.
	EmployeesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeString},
	}
	// EmployeesTable holds the schema information for the "employees" table.
	EmployeesTable = &schema.Table{
		Name:        "employees",
		Columns:     EmployeesColumns,
		PrimaryKey:  []*schema.Column{EmployeesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// PatientsColumns holds the columns for the "patients" table.
	PatientsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "gender", Type: field.TypeString},
	}
	// PatientsTable holds the schema information for the "patients" table.
	PatientsTable = &schema.Table{
		Name:        "patients",
		Columns:     PatientsColumns,
		PrimaryKey:  []*schema.Column{PatientsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// StatisticsColumns holds the columns for the "statistics" table.
	StatisticsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "area_statistic", Type: field.TypeInt, Nullable: true},
		{Name: "carrier_statistic", Type: field.TypeInt, Nullable: true},
		{Name: "contagious_statistic", Type: field.TypeInt, Nullable: true},
		{Name: "employee_statistic", Type: field.TypeInt, Nullable: true},
		{Name: "patient_statistic", Type: field.TypeInt, Nullable: true},
	}
	// StatisticsTable holds the schema information for the "statistics" table.
	StatisticsTable = &schema.Table{
		Name:       "statistics",
		Columns:    StatisticsColumns,
		PrimaryKey: []*schema.Column{StatisticsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "statistics_areas_statistic",
				Columns: []*schema.Column{StatisticsColumns[1]},

				RefColumns: []*schema.Column{AreasColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "statistics_carriers_statistic",
				Columns: []*schema.Column{StatisticsColumns[2]},

				RefColumns: []*schema.Column{CarriersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "statistics_contagious_statistic",
				Columns: []*schema.Column{StatisticsColumns[3]},

				RefColumns: []*schema.Column{ContagiousColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "statistics_employees_statistic",
				Columns: []*schema.Column{StatisticsColumns[4]},

				RefColumns: []*schema.Column{EmployeesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "statistics_patients_statistic",
				Columns: []*schema.Column{StatisticsColumns[5]},

				RefColumns: []*schema.Column{PatientsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AreasTable,
		CarriersTable,
		ContagiousTable,
		EmployeesTable,
		PatientsTable,
		StatisticsTable,
	}
)

func init() {
	StatisticsTable.ForeignKeys[0].RefTable = AreasTable
	StatisticsTable.ForeignKeys[1].RefTable = CarriersTable
	StatisticsTable.ForeignKeys[2].RefTable = ContagiousTable
	StatisticsTable.ForeignKeys[3].RefTable = EmployeesTable
	StatisticsTable.ForeignKeys[4].RefTable = PatientsTable
}
