// Code generated by entc, DO NOT EDIT.

package carrier

const (
	// Label holds the string label denoting the carrier type in the database.
	Label = "carrier"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"

	// EdgeStatistic holds the string denoting the statistic edge name in mutations.
	EdgeStatistic = "statistic"

	// Table holds the table name of the carrier in the database.
	Table = "carriers"
	// StatisticTable is the table the holds the statistic relation/edge.
	StatisticTable = "statistics"
	// StatisticInverseTable is the table name for the Statistic entity.
	// It exists in this package in order to avoid circular dependency with the "statistic" package.
	StatisticInverseTable = "statistics"
	// StatisticColumn is the table column denoting the statistic relation/edge.
	StatisticColumn = "carrier_statistic"
)

// Columns holds all SQL columns for carrier fields.
var Columns = []string{
	FieldID,
	FieldName,
}

var (
	// NameValidator is a validator for the "Name" field. It is called by the builders before save.
	NameValidator func(string) error
)
