// Code generated by entc, DO NOT EDIT.

package area

const (
	// Label holds the string label denoting the area type in the database.
	Label = "area"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"

	// EdgeStatistic holds the string denoting the statistic edge name in mutations.
	EdgeStatistic = "statistic"

	// Table holds the table name of the area in the database.
	Table = "areas"
	// StatisticTable is the table the holds the statistic relation/edge.
	StatisticTable = "statistics"
	// StatisticInverseTable is the table name for the Statistic entity.
	// It exists in this package in order to avoid circular dependency with the "statistic" package.
	StatisticInverseTable = "statistics"
	// StatisticColumn is the table column denoting the statistic relation/edge.
	StatisticColumn = "area_statistic"
)

// Columns holds all SQL columns for area fields.
var Columns = []string{
	FieldID,
	FieldName,
}
